apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netbird-agent.fullname" . }}
  labels:
    {{- include "netbird-agent.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "netbird-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "netbird-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.runtimeClass.pods }}
      runtimeClassName: {{ .Values.runtimeClass.pods }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "netbird-agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.agent.caEnableInitPreConfig }}
      initContainers:
        - name: {{ .Chart.Name }}-init-config
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.agent.caEnableRootless }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}{{ .Values.image.tagSuffixRootless }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NB_MANAGEMENT_URL
              value: {{ .Values.agent.managementUrl | default "https://api.netbird.io:443" }}
            - name: NB_ADMIN_URL
              value: {{ .Values.agent.adminUrl | default "https://app.netbird.io:443" }}
          volumeMounts:
            - name: "{{ .Release.Name }}-data"
              mountPath: "/var/lib/netbird"
            - name: {{ .Release.Name }}-init-entrypoint-script
              mountPath: /usr/local/bin/netbird-entrypoint.sh
              subPath: netbird-entrypoint.sh
              readOnly: true
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.agent.caEnableRootless }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}{{ .Values.image.tagSuffixRootless }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- with .Values.service.metricsPort }}
            - name: metrics
              containerPort: {{ . }}
              protocol: TCP
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- if or $.Values.env $.Values.additionalEnvSecrets }}
            {{- range $key, $value := $.Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $secret := $.Values.additionalEnvSecrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret }}
                  key: {{ $key | quote }}
            {{- end }}
          {{- end }}
            - name: NB_MANAGEMENT_URL
              value: {{ .Values.agent.managementUrl | default "https://api.netbird.io:443" }}
            - name: NB_ADMIN_URL
              value: {{ .Values.agent.adminUrl | default "https://app.netbird.io:443" }}
            - name: NB_LOG_LEVEL
              value: {{ .Values.agent.logLevel | default "info" }}
            - name: NB_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NB_SETUP_KEY
              valueFrom:
                secretKeyRef:
                  name: netbird-setup-key
                  key: key
          {{- if .Values.agent.caEnableRootless }}
            - name: NB_USE_NETSTACK_MODE
              value: "true"
            - name: NB_ENABLE_NETSTACK_LOCAL_FORWARDING
              value: "true"
            - name: NB_DISABLE_DNS
              value: "true"
            - name: NB_DAEMON_ADDR
              value: "unix:///var/lib/netbird/netbird.sock"
            - name: NB_SOCKS5_LISTENER_PORT
              value: {{ .Values.agent.socksPort | default "1080" | quote }}
            - name: NB_LOG_FILE
              value: "console,/var/lib/netbird/client.log"
          {{- else }}
            - name: NB_LOG_FORMAT
              value: {{ .Values.agent.logFormat | default "console" }}
          {{- end }}
          volumeMounts:
            - name: "{{ .Release.Name }}-data"
              mountPath: "/var/lib/netbird"
      volumes:
      {{- include "common.app.pvc" . | nindent 8 }}
      {{- if .Values.agent.caEnableInitPreConfig }}
        - name: {{ .Release.Name }}-init-entrypoint-script
          configMap:
            name: {{ .Release.Name }}-init-entrypoint
            defaultMode: 0555
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
