apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "netbird-agent.fullname" . }}
  labels:
    {{- include "netbird-agent.labels" . | nindent 4 }}
rules: []
#  - apiGroups: [""]
#    resources: ["pods"]
#    verbs: ["get", "list"]
