apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "netbird-agent.fullname" . }}
  labels:
    {{- include "netbird-agent.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "netbird-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "netbird-agent.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
