{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "coturn-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coturn-server.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames:
  - {{ .Values.existingTurnSecret | default "turn-coturn-creds" }}
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
  resourceNames:
  - coturn-server-config
{{- end }}
