{{- if and .Values.turn.enabled (empty .Values.existingTurnSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: turn-coturn-creds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coturn-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: coturn
type: Opaque
data:
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "turn-coturn-creds") }}
{{- $defUsr := "self" }}
{{- if $existingSecret }}
  password: {{ index $existingSecret.data "password" }}
  user: {{ index $existingSecret.data "user" }}
{{- else }}
  password: {{ randAlphaNum 64 | sha256sum | b64enc | quote }}
  user: {{ $defUsr | b64enc | quote  }}
{{- end -}}
{{- end }}
