{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "netbird-management.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird-management.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
  resourceNames:
  - {{ .Values.existingRelayAuthSecret | default "netbird-relay-auth-secret" }}
  - {{ .Values.existingEncryptionKeySecret | default "netbird-datasrc-encryption" }}
  - {{ .Values.existingAuthentikOidcSecret | default "netbird-authentik-oidc" }}
  - {{ .Values.existingAuthentikDeviceOidcSecret | default "netbird-authentik-device-oidc" }}
  - {{ .Values.existingTurnSecret | default "turn-creds-and-secret" }}
  - {{ .Values.postgresql.cnpgCluster.appConnectionSecretName }}
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
  resourceNames:
  - netbird-management-config
{{- end }}
