{{- if .Values.rbac.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netbird-management.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird-management.labels" . | nindent 4 }}
{{- end }}
