{{- define "libchart-cnps.CiliumNetworkPolicy.00-namespace--all-ingress-egress-deny.tpl" -}}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Release.Name | printf "%s-%s--00-namespace--all-ingress-egress-deny" .Chart.Name }}
spec:
  endpointSelector: {}
  ingress:
    - {}
  egress:
    - {}
{{- end -}}
{{- define "libchart-cnps.CiliumNetworkPolicy.00-namespace--all-ingress-egress-deny" -}}
{{- include "libchart-cnps.util.merge" (append . "libchart-cnps.CiliumNetworkPolicy.00-namespace--all-ingress-egress-deny.tpl") -}}
{{- end -}}
