{{- /*
Returns an app-specific policy. This need to be overriden by the application chart.
It's here to provide a scaffold for your application-specific chart.
Therefore, it would block ingress/egress traffic when unconfigured.
*/}}
{{ define "libchart-cnps.CiliumNetworkPolicies-AppSet" }}
{{ include "libchart-cnps.util.merge" (append . "libchart-cnps.CiliumNetworkPolicy.03-app-traffic.tpl") }}
{{ end }}
