{{- if .Values.turn.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coturn-server.fullname" . }}-turn
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coturn-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: coturn
spec:
  replicas: {{ .Values.turn.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "coturn-server.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: coturn
  template:
    metadata:
      labels:
        {{- include "coturn-server.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: coturn
      annotations:
        prometheus.io/scrape: "true"
        checksum/values: {{ print .Values | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/configmaps/turn-config.yaml") . | sha256sum }}
    spec:
      {{- if .Values.runtimeClass.pods }}
      runtimeClassName: {{ .Values.runtimeClass.pods }}
      {{- end }}
      securityContext:
        runAsNonRoot: {{ .Values.turn.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.turn.securityContext.runAsUser }}
        runAsGroup: {{ .Values.turn.securityContext.runAsUser }}
        fsGroup: {{ .Values.turn.securityContext.fsGroup }}
        seccompProfile:
          type: RuntimeDefault

      serviceAccountName: {{ include "coturn-server.serviceAccountName" . }}

      initContainers:
      - name: coturn-init-config
        image: "{{ .Values.turn.initConfig.image.repository }}:{{ .Values.turn.initConfig.image.tag }}"
        imagePullPolicy: {{ .Values.turn.initConfig.image.pullPolicy }}

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: {{ .Values.turn.securityContext.readOnlyRootFilesystem }}
          runAsNonRoot: {{ .Values.turn.securityContext.runAsNonRoot }}
          runAsUser: {{ .Values.turn.securityContext.runAsUser }}
          capabilities:
            drop:
            - ALL

        command: ["/bin/bash", "-c"]
        args:
        - |
          set -e
          # Generate turnserver.conf.
          echo "Generating turnserver.conf...."
          envsubst < /etc/coturn-config-template/turnserver.conf.tmpl | cat > /etc/coturn/config/turnserver.conf

          if [[ "true" == $CA_DEBUG_OUTPUT ]]; then
            echo "Generated configuration:"
            cat /etc/coturn/config/turnserver.conf
          fi
          echo "Init process finished."

        env:
        - name: CA_DEBUG_OUTPUT
          value: "{{ .Values.global.caDebugOutput }}"
        - name: TURN_EXT_IP
          value: {{ .Values.turn.extIp | quote }}
        - name: TURN_DOMAIN
          value: "{{ .Values.turn.domain | default .Values.global.domain }}"
        - name: TURN_PORT
          value: "{{ .Values.turn.port | default 3478 }}"
        - name: TURN_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.existingTurnSecret | default "turn-coturn-creds" }}
              key: user
        - name: TURN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.existingTurnSecret | default "turn-coturn-creds" }}
              key: password
        volumeMounts:
        - name: {{ .Release.Name }}-turn-config
          mountPath: /etc/coturn/config
        - name: {{ .Release.Name }}-turn-config-template
          mountPath: /etc/coturn-config-template

      affinity:
        podAntiAffinity:
          {{- if eq .Values.turn.affinity.podAntiAffinity "preferred" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          {{- else }}
          requiredDuringSchedulingIgnoredDuringExecution:
          {{- end }}
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - {{ include "coturn-server.name" . }}
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - coturn
              topologyKey: kubernetes.io/hostname

      containers:
      - name: coturn
        image: "{{ .Values.turn.image.repository }}:{{ .Values.turn.image.tag }}"
        imagePullPolicy: {{ .Values.turn.image.pullPolicy }}

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: {{ .Values.turn.securityContext.readOnlyRootFilesystem }}
          runAsNonRoot: {{ .Values.turn.securityContext.runAsNonRoot }}
          runAsUser: {{ .Values.turn.securityContext.runAsUser }}
          capabilities:
            drop:
            - ALL

        ports:
        - name: stun-udp
          containerPort: {{ .Values.turn.port | default 3478 }}
          protocol: UDP
        - name: metrics
          containerPort: {{ .Values.turn.metricsPort }}
          protocol: TCP

        {{- if .Values.turn.probes.liveness.enabled }}
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: {{ .Values.turn.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.turn.probes.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.turn.probes.liveness.timeoutSeconds }}
          failureThreshold: {{ .Values.turn.probes.liveness.failureThreshold }}
        {{- end }}

        {{- if .Values.turn.probes.readiness.enabled }}
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: {{ .Values.turn.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.turn.probes.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.turn.probes.readiness.timeoutSeconds }}
          failureThreshold: {{ .Values.turn.probes.readiness.failureThreshold }}
        {{- end }}

        resources:
          requests:
            cpu: {{ .Values.turn.resources.requests.cpu }}
            memory: {{ .Values.turn.resources.requests.memory }}
          limits:
            cpu: {{ .Values.turn.resources.limits.cpu }}
            memory: {{ .Values.turn.resources.limits.memory }}

        command: [ "docker-entrypoint.sh" ]
        {{- if not .Values.turn.extIp }}
        args: [
          "-c",
          "/etc/coturn/config/turnserver.conf",
          "--external-ip=$(detect-external-ip)"
        ]
        {{- else }}
        args: [
          "-c",
          "/etc/coturn/config/turnserver.conf"
        ]
        {{- end }}
        volumeMounts:
          - name: {{ .Release.Name }}-turn-tmp
            mountPath: /etc/coturn/tmp
          - name: {{ .Release.Name }}-turn-data
            mountPath: /etc/coturn/data
          - name: {{ .Release.Name }}-turn-config
            mountPath: /etc/coturn/config
            readOnly: true

      volumes:
        {{- include "common.app.turn.pvc" . | nindent 8 }}
        - name: {{ .Release.Name }}-turn-tmp
          emptyDir: {}
        - name: {{ .Release.Name }}-turn-config
          emptyDir: {}
        - name: {{ .Release.Name }}-turn-config-template
          configMap:
            name: coturn-turn-config
            defaultMode: 0644

      terminationGracePeriodSeconds: 30
{{- end }}
