{{- if empty .Values.existingAuthentikDeviceOidcSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: netbird-authentik-device-oidc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird-management.labels" . | nindent 4 }}
    app.kubernetes.io/component: device-oidc
type: Opaque
data:
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "netbird-authentik-device-oidc") }}
{{- if $existingSecret }}
  client-id: {{ index $existingSecret.data "client-id" }}
  client-secret: {{ index $existingSecret.data "client-secret" }}
{{- else }}
  client-id: {{ .Values.authentik.device.clientId | b64enc | quote }}
  client-secret: {{ .Values.authentik.device.clientSecret | b64enc | quote }}
{{- end -}}
{{- end }}
