{{- if empty .Values.existingEncryptionKeySecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: netbird-datasrc-encryption
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird-management.labels" . | nindent 4 }}
type: Opaque
data:
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "netbird-datasrc-encryption") }}
{{- if $existingSecret }}
  encryptionKey: {{ index $existingSecret.data "encryptionKey" }}
{{- else }}
  encryptionKey: {{ randAlpha 32 | b64enc }}
{{- end -}}
{{- end }}
