{{- if empty .Values.existingRelayAuthSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: netbird-relay-auth-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird-management.labels" . | nindent 4 }}
    app.kubernetes.io/component: relay
type: Opaque
data:
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "netbird-relay-auth-secret") }}
{{- if $existingSecret }}
  secret: {{ index $existingSecret.data "secret" }}
{{- else }}
  secret: {{ randAlphaNum 64 | sha256sum | b64enc | quote }}
{{- end -}}
{{- end }}
