{{- if empty .Values.existingTurnSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: turn-creds-and-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird-management.labels" . | nindent 4 }}
    app.kubernetes.io/component: coturn-turn
type: Opaque
data:
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "turn-creds-and-secret") }}
{{- if $existingSecret }}
  password: {{ index $existingSecret.data "password" }}
  secret: {{ index $existingSecret.data "secret" }}
{{- else }}
  password: {{ randAlphaNum 64 | sha256sum | b64enc | quote }}
  secret: {{ randAlphaNum 64 | sha256sum | b64enc | quote }}
{{- end -}}
{{- end }}
