{{- if and .Values.ingress.enabled (or .Values.signal.enabled .Values.management.enabled .Values.relay.enabled)}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "netbird-management.fullname" . }}-websocket
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird-management.labels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.issuer.name }}
    {{- with .Values.ingress.additionalAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts: ["{{ .Values.global.domain }}"]
      secretName: {{ include "netbird-management.fullname" . }}-tls
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
        {{- if .Values.signal.enabled }}
          - path: /ws-proxy/signal
            pathType: Prefix
            backend:
              service:
                name: {{ include "netbird-management.fullname" . }}-signal
                port:
                  number: {{ .Values.signal.service.port }}
        {{- end }}
        {{- if .Values.management.enabled }}
          - path: /ws-proxy/management
            pathType: Prefix
            backend:
              service:
                name: {{ include "netbird-management.fullname" . }}-management
                port:
                  number: {{ .Values.management.service.port }}
        {{- end }}
        {{- if .Values.relay.enabled }}
          - path: /relay
            pathType: Prefix
            backend:
              service:
                name: {{ include "netbird-management.fullname" . }}-relay
                port:
                  number: {{ .Values.relay.service.port }}
        {{- end }}
{{- end }}
