{{- if .Values.management.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird-management.fullname" . }}-management
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird-management.labels" . | nindent 4 }}
    app.kubernetes.io/component: management
spec:
  type: {{ .Values.management.service.type }}
  ports:
  - port: {{ .Values.management.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.management.service.metricsPort }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "netbird-management.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: management
{{- end }}
