{{- if .Values.signal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird-management.fullname" . }}-signal
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird-management.labels" . | nindent 4 }}
    app.kubernetes.io/component: signal
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.signal.service.grpcPort }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: {{ .Values.signal.service.port }}
    targetPort: signal
    protocol: TCP
    name: signal
  - port: {{ .Values.signal.service.metricsPort }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "netbird-management.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: signal
{{- end }}
