{{- if .Values.turn.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird-management.fullname" . }}-turn
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird-management.labels" . | nindent 4 }}
    app.kubernetes.io/component: turn
spec:
  type: {{ .Values.turn.service.type }}
  ports:
  - port: {{ .Values.turn.service.port | default 3478 }}
    targetPort: stun-udp
    protocol: UDP
    name: stun-udp
  - port: {{ .Values.turn.service.metricsPort }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "netbird-management.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: turn
{{- end }}
