apiVersion: v2
name: netbird-management
description: A Helm chart for an easier netbird management stack (https://netbird.io) deployment at kubernetes.
type: application
# renovate: bumpVersion
version: 1.4.3
# renovate image=netbirdio/management
appVersion: "0.61.2"
home: https://github.com/CodeAdminDe/helm-charts
keywords:
  - netbird
  - vpn
  - mesh-network
  - wireguard
  - zero-trust
  - sso
  - postgresql
  - cnpg
  - cloud-native
maintainers:
  - name: Frederic Roggon
    email: frederic.roggon@codeadmin.de
    url: https://github.com/CodeAdminDe
annotations:
  category: Networking
  kubeVersion: ">=1.33.0"
  securityContext: "required"
dependencies:
  - name: libchart-cnps
    version: 0.2.1
    repository: https://codeadminde.github.io/helm-charts
    alias: libchart-cnps
    condition: libchartCnps.enabled
