---
apiVersion: v2
name: redis
# renovate: bumpVersion
version: 0.4.0
# renovate: image=library/redis
appVersion: "8.6.0"
description: A Helm chart for Redis k8s deployment, based on library/redis
home: https://github.com/CodeAdminDe/helm-charts
keywords:
  - redis
  - database
  - cache
maintainers:
  - name: Frederic Roggon
    email: frederic.roggon@codeadmin.de
    url: https://github.com/CodeAdminDe
